const express = require("express");
const router = express.Router();
const { createCourse } = require("../controller/createCourse");
const { getAllCourses } = require("../controller/getallCourses");
const { getCoursesData } = require("../controller/getCourseData");
const { addCourseVideo } = require("../controller/addCourseVideo");
router.post("/createcourse", createCourse);
router.get("/getallcourses", getAllCourses);
router.get("/getcoursedata/:id", getCoursesData);
router.post("/addvideo/:id", addCourseVideo);
module.exports = router;
